#!/bin/bash
#
# Copyright 2018 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

MF_LEVEL=$(git rev-parse --abbrev-ref HEAD)

mkdir -p .game_data/state
RECORD_HINT_ACCESS="${MF_LEVEL}_hint_log"

# Record that a hint has been requested
echo "Hint accessed" >> .game_data/state/"${RECORD_HINT_ACCESS}"

# How many hint files do we have?
get_number_of_hint_files() {
    find .game_data -name "${MF_LEVEL}_hint*txt" | wc -l
}

# How many times has this script been invoked?
get_hint_count() {
    wc -l < ".game_data/state/${RECORD_HINT_ACCESS}" | tr -d '[:space:]'
}

# Display the correct hint (cycle through the hint files)
COUNT=$(get_hint_count)
if [[ ${COUNT} -eq 1 ]]; then
    cat ".game_data/${MF_LEVEL}_hint.txt"
else
    cat ".game_data/${MF_LEVEL}_hint${COUNT}.txt"
fi


# Once all hint files have been shown we want to over again with the first
# hint file.  We do this by deleting the file which logs the hint access.
NUM_FILES=$(get_number_of_hint_files)
if [[ ${NUM_FILES} -eq ${COUNT} ]] ; then
    rm ".game_data/state/${RECORD_HINT_ACCESS}"
fi
