#!/bin/bash
#
# Copyright 2018 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
MF_LEVEL=$(git rev-parse --abbrev-ref HEAD)

# If the user gets himself into a strange state, give them some help.
if [[ "${MF_LEVEL}" == "HEAD" ]]; then
    clear && cat .game_data/${MF_LEVEL}_hint.txt
    exit 0
fi

# invoke level specific setup after 'git checkout'
if [[ -f ".game_data/${MF_LEVEL}_post_checkout_setup.sh" ]]; then
    ".game_data/${MF_LEVEL}_post_checkout_setup.sh" >/dev/null 2>&1
fi

# During a rebase we might be in a detached head state.
if [[ -f .game_data/${MF_LEVEL}_room.txt ]]; then
    clear && cat .game_data/${MF_LEVEL}_room.txt
fi
