#!/bin/bash
#
# Copyright 2018 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
MF_LEVEL=$(git rev-parse --abbrev-ref HEAD)
(.game_data/${MF_LEVEL}_validation.sh)

STATUS=$?
if [ ${STATUS} -eq 0 ]; then
    (.game_scripts/unlock_next_level.sh)
    exit 0
else
    RED='\033[0;31m'
    NO_COLOR='\033[0m'
    printf "${RED}Incorrect - why not try again?${NO_COLOR}\n"
    exit 1
fi
