#!/bin/bash
#
# Copyright 2018 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

isMagicPotionLevel (){
    POTION_BRANCH_NAME=$(cat .game_info/branches.txt | grep magic_potion)
    git branch | grep "no branch, rebasing ${POTION_BRANCH_NAME}"
}

# Are we currently on the magic_potion branch that requires a rebase?
isMagicPotionLevel
STATUS=$?

if [ ${STATUS} -eq 0   ]
then
    echo "Rebase is not needed to solve this level. Please try to solve the level differently"
    exit 1
else
    echo "Rebase for magic potion level: You are on the right track"
    exit 0
fi
